[project]
name = "funread"
version = "1.1.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [ "dominate>=2.9.1", "funfile>=1.0.11", "funutil>=1.0.25",]
